apiVersion: skaffold/v2beta28
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./k8s/*
build:
  artifacts:
    - image: nestjs/auth
      context: .
      docker:
        dockerfile: Dockerfile.auth
      sync:
        manual:
          - src: 'apps/auth/scr/**/*.ts'
            dest: .