apiVersion: skaffold/v2beta28
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./k8s/*
build:
  artifacts:
    - image: nestjs/auth
      context: .
      docker:
        dockerfile: Dockerfile.auth
      sync:
        manual:
          - src: 'apps/auth/scr/**/*.ts'
            dest: .
    - image: nestjs/tickets
      context: .
      docker:
        dockerfile: Dockerfile.tickets
      sync:
        manual:
          - src: 'apps/tickets/scr/**/*.ts'
            dest: .
    - image: nestjs/orders
      context: .
      docker:
        dockerfile: Dockerfile.orders
      sync:
        manual:
          - src: 'apps/orders/scr/**/*.ts'
            dest: .