FROM node:18.12.1-alpine AS development

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install

COPY ./ .

# RUN npm run build:auth

# CMD ["node", "dist/apps/auth/main"]
CMD ["npm", "run", "start", "auth"]